// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWZPY59E3s9_DIEcbKDGW3TcT-JRKepoI',
    appId: '1:795448779156:web:13a8a5e48241395ca96f81',
    messagingSenderId: '795448779156',
    projectId: 'wish-watch',
    authDomain: 'wish-watch.firebaseapp.com',
    storageBucket: 'wish-watch.appspot.com',
    measurementId: 'G-FN6XGNC6NT',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6S1ZUTxw38UJRsxGadsk94B5M5y_Fj2U',
    appId: '1:795448779156:ios:8ab071caa1253769a96f81',
    messagingSenderId: '795448779156',
    projectId: 'wish-watch',
    storageBucket: 'wish-watch.appspot.com',
    iosBundleId: 'com.example.flutter470project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6S1ZUTxw38UJRsxGadsk94B5M5y_Fj2U',
    appId: '1:795448779156:ios:8ab071caa1253769a96f81',
    messagingSenderId: '795448779156',
    projectId: 'wish-watch',
    storageBucket: 'wish-watch.appspot.com',
    iosBundleId: 'com.example.flutter470project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWZPY59E3s9_DIEcbKDGW3TcT-JRKepoI',
    appId: '1:795448779156:web:39eb93826a250b7ea96f81',
    messagingSenderId: '795448779156',
    projectId: 'wish-watch',
    authDomain: 'wish-watch.firebaseapp.com',
    storageBucket: 'wish-watch.appspot.com',
    measurementId: 'G-CWRZTCZE38',
  );

}